STORAGE: 
  ENGINE: POSTGRES
  USERHOST: localhost
  FRIENDHOST: localhost
  PORT: 5432
  USERNAME: connect_b_users
  FRIENDNAME: connect_b_friends
  USERUSERNAME: connect_b
  USERPASSWORD: connect_b
  FRIENDUSERNAME: connect_b
  FRIENDPASSWORD: connect_b

SERVER:
  HOST: localhost
  PORT: 8080